###### REGRESSION (MODULE I) ######

#' Read REBOOT input tables
#'
#' @description Reads tabular input files used across REBOOT modules. This function is a wrapper around
#' \code{utils::read.delim()} with standardized parameters used internally by the package.
#'
#' @param file Character. Path to input table file.
#' @param sep Field separator (default: \code{tab}).
#' @param row.names Logical. Whether the first column should be used as row names (default: \code{TRUE}).
#'
#' @return A data.frame containing the imported table.
#' @export
read_reboot_table <- function(file, sep = "\t", row.names = TRUE) {
  # Validates input file
  if (!is.character(file) || length(file) != 1) {stop("'file' must be a single character string with the table PATH")}
  if (!file.exists(file)) {stop("Input file does not exist")}
  
  # Validates row.names parameter
  if (!is.logical(row.names) || length(row.names) != 1) {stop("'row.names' must be TRUE or FALSE")}
  
  # Reads table
  if (isTRUE(row.names))
  {
    data <- utils::read.delim(file = file, header = TRUE, sep = sep, row.names = 1, check.names = FALSE)
  } else {
    data <- utils::read.delim(file = file, header = TRUE, sep = sep, check.names = FALSE)
  }
  
  return(data)
}

#' Load a REBOOT object from an RDS file
#'
#' @description Loads a REBOOT object previously saved with \code{write_reboot_rds()}.
#'
#' @param file Character. Path to an REBOOT (`reboot_signature`, or `reboot_survival`, or `reboot_complete`) RDS file.
#'
#' @return A REBOOT object.
#' @export
read_reboot_rds <- function(file) {
  # Validates file
  if (!is.character(file) || length(file) != 1 || nchar(file) == 0) {stop("'file' must be a single non-empty character string")}
  
  # Checks file existence
  if (!file.exists(file)) {stop("File does not exist: ", file)}
  
  # Loads object
  object <- readRDS(file)
  
  # Validates loaded object
  valid_classes <- c("reboot_signature", "reboot_survival", "reboot_complete")
  if (!inherits(object, valid_classes))
  {
    stop("The loaded file is not a valid REBOOT object. Expected classes: ", paste(valid_classes, collapse = ", "))
  }
  
  return(object)
}

#' Save a REBOOT object as an RDS file
#'
#' @description Saves a REBOOT object generated by \code{rebootRegression()}, \code{rebootSurvival()},
#' or \code{rebootComplete()} into a compressed RDS file.
#'
#' @param object A REBOOT object of class `reboot_signature`, `reboot_survival`, or `reboot_complete`.
#' @param file Character. Output file name.
#' @param compress Character. Compression method passed to \code{saveRDS()} (Default: \code{"xz"}).
#'
#' @return Invisibly returns the output file path.
#' @export
write_reboot_rds <- function(object, file, compress = "xz") {
  # Validates object
  valid_classes <- c("reboot_signature", "reboot_survival", "reboot_complete")
  if (!inherits(object, valid_classes))
  {
    stop("'object' must be a valid REBOOT object of class: ", paste(valid_classes, collapse = ", "))
  }
  
  # Validates file
  if (!is.character(file) || length(file) != 1 || nchar(file) == 0) {stop("'file' must be a single non-empty character string")}
  
  # Validates compression method
  valid_compress <- c("gzip", "bzip2", "xz", FALSE)
  if (!compress %in% valid_compress) {stop("'compress' must be one of: ", paste(valid_compress, collapse = ", "))}
  
  # Adds .rds extension if missing
  if (!grepl("\\.rds$", file, ignore.case = TRUE)) {file <- paste0(file, ".rds")}
  
  # Saves object
  saveRDS(object = object, file = file, compress = compress)
  
  invisible(file)
}

#' Export REBOOT signature to file
#'
#' @description Writes REBOOT signature table from a `reboot_signature` object generated by \code{rebootRegression()} to disk.
#'
#' @param x A `reboot_signature` or `reboot_survival` object or a valid data frame.
#' @param file Output file path.
#' @param sep Field separator (default: \code{tab}).
#' @param row.names Logical. Whether to write row names (default: \code{FALSE}).
#' @param quote Logical. Whether to quote strings (default: \code{FALSE}).
#' @param ... Additional arguments passed to \code{utils::write.table()}.
#'
#' @return Invisibly returns the input object.
#' @export
write_reboot_signature <- function(x, file, sep = "\t", row.names = FALSE, quote = FALSE, ...) {
  # Extracts signature table according to input type
  if (inherits(x, c("reboot_signature", "reboot_survival")))
  {
    df <- as.data.frame(x)
  } else if (is.data.frame(x)) {
    required_cols <- c("feature", "coefficient")
    if (!all(required_cols %in% colnames(x))) {stop("Data.frame must contain columns: 'feature' and 'coefficient'")}
    df <- x
  } else {stop("Object must be of class 'reboot_signature' or 'reboot_survival' or be a valid data.frame")}
  
  # Deals with file parameter
  if (missing(file) || is.null(file)) {
    message("No filename provided. Using 'reboot_signature.txt'...")
    file <- "reboot_signature.txt"
  } else if (!is.character(file) || length(file) != 1) {
    stop("`file` must be a single character string")
  }
  
  # Checks file extension
  ext <- tolower(tools::file_ext(file))
  
  # Adds default extension if missing
  if (ext == "") {
    warning("No file extension detected. Using '.txt' with tab separator...")
    ext <- "txt"
    file <- paste0(file, ".", ext)
  }
  
  # Checks compatibility between extension and separator
  if (ext %in% c("txt", "tsv") && sep != "\t") {
    warning(sprintf("File extension '%s' suggests tab-separated format, but 'sep' is not '\\t'.", ext))
  } else if (ext == "csv" && sep != ",") {
    warning(sprintf("File extension '%s' usually uses comma separator, but 'sep' is not ','.", ext))
  }
  
  # Writes signature
  utils::write.table(df, file = file, sep = sep, row.names = row.names, quote = quote, ...)
  
  invisible(x)
}

#' Write Reboot execution metadata to JSON
#'
#' @description Exports execution metadata, user parameters, and session information to a JSON file for reproducibility.
#'
#' @param module Character. Name of the executed Reboot module.
#' Must be either "rebootRegression", or "rebootSurvival" or "rebootComplete".
#' @param outprefix Character. Output prefix used to generate the JSON file.
#' @param parameters Named list containing user-defined parameters.
#' @param command Character. Command line used to run the analysis (optional).
#' Use \code{"none"} to disable command export.
#'
#' @return Invisibly returns the metadata list.
#' @export
write_reboot_metadata <- function(module, outprefix, parameters, command = NULL)
{
  # Validates module
  valid_modules <- c("rebootRegression", "rebootSurvival", "rebootComplete")
  if (!is.character(module) || length(module) != 1) {stop("'module' must be a character string")}
  if (!module %in% valid_modules) {stop("'module' must be one of: ", paste(valid_modules, collapse = ", "))}
  
  # Validates output prefix
  if (!is.character(outprefix) || length(outprefix) != 1) {stop("'outprefix' must be a character string")}
  
  # Validates parameters
  if (!is.list(parameters)) {stop("'parameters' must be a named list")}
  
  # Validates command
  if (!is.null(command) && (!is.character(command) || length(command) != 1))
  {
    stop("'command' must be NULL, 'none', or a character string")
  }
  
  # Captures command automatically
  if (is.null(command)) {command <- paste(commandArgs(), collapse = " ")}
  
  # Disables command export
  if (identical(command, "none")) {command <- NULL}
  
  # Extracts installed packages
  installed_packages <- as.data.frame(utils::installed.packages()[, c("Package", "Version")], stringsAsFactors = FALSE)
  
  # Builds metadata object
  metadata <- list(
    module = module,
    timestamp = as.character(Sys.time()),
    command = command,
    parameters = parameters,
    session = list(R.version = R.version.string, platform = R.version$platform, packages = installed_packages)
  )
  
  # Defines output file name
  output_file <- switch(
    module,
    rebootRegression = paste0(outprefix, "_metadata_regression.json"),
    rebootSurvival = paste0(outprefix, "_metadata_survival.json"),
    rebootComplete = paste0(outprefix, "_metadata_complete.json")
  )
  
  # Writes JSON file
  jsonlite::write_json(x = metadata, path = output_file, pretty = TRUE, auto_unbox = TRUE, null = "null")
  
  invisible(metadata)
}

#' Generate a REBOOT analysis report
#'
#' @description Generates a detailed PDF or HTML report summarizing REBOOT analyses, including parameters used,
#' summary statistics, filtering steps, models generation, bootstrap information, figures and tables.
#'
#' @param object Either:
#' \itemize{
#'   \item A \code{"reboot_signature"} result object from module I - regression
#'   \item A \code{"reboot_survival"} result object from module II - survival
#'   \item A \code{"reboot_complete"} result object from both modules - complete workflow
#' }
#' @param format Output report format. Accepts:
#' \itemize{
#'   \item \code{TRUE} (default; generates PDF)
#'   \item \code{"PDF"}
#'   \item \code{"HTML"}
#' }
#' @param file Character. Output file path (Default: \code{NULL}).
#' @param title Character. Report title (Default: \code{"REBOOT Report"}).
#' @param author Character. Report author (Default: \code{"your username from Sys.info()"}).
#'
#' @return Invisibly returns output report path.
#' @export
write_reboot_report <- function(object, format = TRUE, file = NULL,
                                title = "REBOOT Report", author = Sys.info()[["user"]])
{
  # Validates object
  valid_object <- any(class(object) %in% c("reboot_signature", "reboot_survival", "reboot_complete"))
  if (!valid_object) {stop("'object' must be a valid 'reboot_signature', 'reboot_survival' or 'reboot_complete' object")}
  
  # Validates title
  if (!is.character(title) || length(title) != 1) {stop("'title' must be a single character string")}
  
  # Validates author
  if (!is.character(author) || length(author) != 1) {stop("'author' must be a single character string")}
  
  # Standardizes format
  if (isTRUE(format)) {format <- "PDF"}
  if (!is.character(format) || length(format) != 1) {stop("'format' must be TRUE, 'PDF', or 'HTML'")}
  format <- toupper(format)
  if (!format %in% c("PDF", "HTML"))
  {
    warning(paste0("Invalid report format: ", format, " detected. Using 'PDF' instead."))
    format <- "PDF"
  }
  
  # Defines extension
  expected_ext <- ifelse(format == "PDF", ".pdf", ".html")
  
  # Defines output file
  if (is.null(file))
  {
    file <- switch(
      class(object)[1],
      reboot_signature = paste0("REBOOT_report_regression", expected_ext),
      reboot_survival  = paste0("REBOOT_report_survival", expected_ext),
      reboot_complete  = paste0("REBOOT_report_complete", expected_ext)
    )
  }
  
  # Validates file
  if (!is.character(file) || length(file) != 1) {stop("'file' must be a single character string")}
  
  # Detects extension
  current_ext <- tolower(tools::file_ext(file))
  
  # Adds extension if absent
  if (current_ext == "")
  {
    file <- paste0(file, expected_ext)
  }
  else if (!current_ext %in% c("pdf", "html"))
  {
    warning(paste0("Invalid file extension: '", current_ext, "' detected. Using '",
                   sub("^\\.", "", expected_ext), "' instead."))
    file <- paste0(tools::file_path_sans_ext(file), expected_ext)
  }
  
  # Extracts output directory and file name
  output_file <- basename(file)
  output_dir <- dirname(file)
  if (!dir.exists(output_dir)) {dir.create(output_dir, recursive = TRUE)}
  
  # Checks Quarto
  if (!requireNamespace("quarto", quietly = TRUE)) {stop("Package 'quarto' must be installed to generate reports")}
  
  # Checks Quarto installation
  quarto_path <- quarto::quarto_path()
  if (is.null(quarto_path) || !nzchar(quarto_path)) {stop("Quarto executable was not found in the system")}
  
  # Retrieves report template
  template <- system.file("quarto/reboot_report.qmd", package = "Reboot")
  if (!file.exists(template)) {stop("Report template file 'reboot_report.qmd' was not found")}
  
  # Creates temporary RDS object
  temp_rds <- tempfile(fileext = ".rds")
  saveRDS(object, temp_rds)
  on.exit(unlink(temp_rds), add = TRUE)
  
  # Defines quarto format
  quarto_format <- ifelse(format == "PDF", "pdf", "html")
  
  # Renders report
  quarto::quarto_render(input = template, output_file = output_file, output_format = quarto_format,
                        execute_dir = output_dir, quiet = FALSE,
                        execute_params = list(reboot_object = temp_rds, title = title, author = author))
  
  # Moves generated report to user-defined directory
  success <- file.rename(from = file.path(dirname(template), output_file), to = file)
  if (!success) {stop("Failed to move generated report to destination directory")}
  
  return(invisible(normalizePath(file, mustWork = FALSE)))
}

###### SURVIVAL (MODULE II) ######

#' Export REBOOT score to file
#'
#' @description Writes REBOOT score tables generated by \code{rebootSurvival()} to disk.
#'
#' This function supports:
#' \itemize{
#'   \item Continuous score tables (\code{scoreCont})
#'   \item Categorized score tables (\code{scoreCat})
#'   \item Optional clinical covariates from multivariate analyses
#' }
#'
#' @param x Either:
#' \itemize{
#'   \item A `reboot_survival` object
#'   \item A valid data.frame containing REBOOT score information and possibly clinical data
#' }
#' @param file Output file path.
#' @param clinics Logical. Whether the output should include clinical data or not (default: \code{FALSE}).
#' @param sep Field separator (default: \code{tab}).
#' @param row.names Logical. Whether to write row names (default: \code{TRUE}).
#' @param quote Logical. Whether to quote strings (default: \code{FALSE}).
#' @param ... Additional arguments passed to \code{utils::write.table()}.
#'
#' @return Invisibly returns the input object.
#' @export
write_reboot_score <- function(x, file, clinics = FALSE, sep = "\t", row.names = TRUE, quote = FALSE, ...) {
  # Extracts score table according to input type
  if (inherits(x, "reboot_survival"))
  {
    if (clinics)
    {
      df <- x$clinical_data
    } else {df <- x$expression_data}
  } else if (is.data.frame(x)) {
    required_cols <- c("OS", "OS.time", "score")
    if (!all(required_cols %in% colnames(x)))
    {
      stop("Data.frame must contain at least the columns: 'OS', 'OS.time', and 'score'")
    }
    df <- x
  } else {stop("Object must be of class 'reboot_survival' or a valid data.frame")}
  
  # Deals with file parameter
  if (missing(file) || is.null(file))
  {
    message("No filename provided. Using 'reboot_score.txt'...")
    file <- "reboot_score.txt"
  } else if (!is.character(file) || length(file) != 1) {
    stop("'file' must be a single character string")
  }
  
  # Checks file extension
  ext <- tolower(tools::file_ext(file))
  
  # Adds default extension if missing
  if (ext == "")
  {
    warning("No file extension detected. Using '.txt' with tab separator...")
    ext <- "txt"
    file <- paste0(file, ".", ext)
  }
  
  # Checks compatibility between extension and separator
  if (ext %in% c("txt", "tsv") && sep != "\t")
  {
    warning(sprintf("File extension '%s' suggests tab-separated format, but 'sep' is not '\\t'.", ext))
  } else if (ext == "csv" && sep != ",") {
    warning(sprintf("File extension '%s' usually uses comma separator, but 'sep' is not ','.", ext))
  }
  
  # Writes table
  utils::write.table(df, file = file, sep = sep, row.names = row.names, quote = quote, ...)
  
  invisible(x)
}

#' Export REBOOT univariate survival results to file
#'
#' @description Writes univariate survival analysis results generated by \code{rebootSurvival()} to disk.
#'
#' @param x Either:
#' \itemize{
#'   \item A `reboot_survival` object
#'   \item A list returned by \code{reboot_uniCox_model()}
#'   \item A valid data.frame containing univariate survival results
#' }
#'
#' @param file Output file path.
#' @param sep Field separator (default: \code{tab}).
#' @param row.names Logical. Whether to write row names (default: \code{FALSE}).
#' @param quote Logical. Whether to quote strings (default: \code{FALSE}).
#' @param ... Additional arguments passed to \code{utils::write.table()}.
#'
#' @return Invisibly returns the input object.
#' @export
write_reboot_univariate <- function(x, file, sep = "\t", row.names = FALSE, quote = FALSE, ...) {
  # Extracts univariate table according to input type
  if (inherits(x, "reboot_survival"))
  {
    df <- x$survival$univariate$table
  } else if (is.list(x) && "table" %in% names(x)) {
    df <- x$table
  } else if (is.data.frame(x)) {
    required_cols <- c("feature", "hazard.ratio", "log.rank.pvalue")
    
    if (!all(required_cols %in% colnames(x)))
    {
      stop("Data.frame must contain at least the following columns: 'feature', 'hazard.ratio', and 'log.rank.pvalue'")
    }
    df <- x
  } else {stop("Input must be a 'reboot_survival' object, a valid univariate result list, or a compatible data.frame")}
  
  # Deals with file parameter
  if (missing(file) || is.null(file))
  {
    message("No filename provided. Using 'reboot_uniCox.txt'...")
    file <- "reboot_uniCox.txt"
  } else if (!is.character(file) || length(file) != 1) {stop("'file' must be a single character string")}
  
  # Checks file extension
  ext <- tolower(tools::file_ext(file))
  
  # Adds default extension if missing
  if (ext == "")
  {
    warning("No file extension detected. Using '.txt' with tab separator...")
    ext <- "txt"
    file <- paste0(file, ".", ext)
  }
  
  # Checks compatibility between extension and separator
  if (ext %in% c("txt", "tsv") && sep != "\t")
  {
    warning(sprintf("File extension '%s' suggests tab-separated format, but 'sep' is not '\\t'.", ext))
  } else if (ext == "csv" && sep != ",") {
    warning(sprintf("File extension '%s' usually uses comma separator, but 'sep' is not ','.", ext))
  }
  
  # Writes table
  utils::write.table(df, file = file, sep = sep, row.names = row.names, quote = quote, ...)
  
  invisible(x)
}

#' Export REBOOT multivariate survival results to file
#'
#' @description Writes multivariate survival analysis results generated by \code{rebootSurvival()} to disk.
#'
#' @param x Either:
#' \itemize{
#'   \item A `reboot_survival` object
#'   \item A list returned by \code{reboot_multiCox_test()}
#'   \item A valid data.frame containing multivariate survival results
#' }
#'
#' @param file Output file path.
#' @param sep Field separator (default: \code{tab}).
#' @param row.names Logical. Whether to write row names (default: \code{FALSE}).
#' @param quote Logical. Whether to quote strings (default: \code{FALSE}).
#' @param ... Additional arguments passed to \code{utils::write.table()}.
#'
#' @return Invisibly returns the input object.
#' @export
write_reboot_multivariate <- function(x, file, sep = "\t", row.names = FALSE, quote = FALSE, ...) {
  # Extracts multivariate table according to input type
  if (inherits(x, "reboot_survival"))
  {
    df <- x$survival$multivariate$table
  } else if (is.list(x) && "table" %in% names(x)) {
    df <- x$table
  } else if (is.data.frame(x)) {
    required_cols <- c("variable", "condition", "univariate.hazard.ratio", "univariate.Cox.pvalue", "univariate.prognosis",
                       "multivariate.hazard.ratio", "multivariate.Cox.pvalue", "multivariate.prognosis")
    if (!all(required_cols %in% colnames(x))) {stop("Data.frame must contain valid multivariate survival analysis columns")}
    df <- x
  } else {stop("Input must be a 'reboot_survival' object, a valid multivariate result list, or a compatible data.frame")}
  
  # Deals with file parameter
  if (missing(file) || is.null(file))
  {
    message("No filename provided. Using 'reboot_multiCox.txt'...")
    file <- "reboot_multiCox.txt"
  } else if (!is.character(file) || length(file) != 1) {stop("'file' must be a single character string")}
  
  # Checks file extension
  ext <- tolower(tools::file_ext(file))
  
  # Adds default extension if missing
  if (ext == "")
  {
    warning("No file extension detected. Using '.txt' with tab separator...")
    ext <- "txt"
    file <- paste0(file, ".", ext)
  }
  
  # Checks compatibility between extension and separator
  if (ext %in% c("txt", "tsv") && sep != "\t")
  {
    warning(sprintf("File extension '%s' suggests tab-separated format, but 'sep' is not '\\t'.", ext))
  } else if (ext == "csv" && sep != ",") {
    warning(sprintf("File extension '%s' usually uses comma separator, but 'sep' is not ','.", ext))
  }
  
  # Writes table
  utils::write.table(df, file = file, sep = sep, row.names = row.names, quote = quote, ...)
  
  invisible(x)
}
